steps:
  - name: 'node:22'
    env:
      - "FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "FIREBASE_APP_CHECK_DEBUG=${_FIREBASE_APP_CHECK_DEBUG}"
      - "FIREBASE_APP_CHECK_SITE_KEY=${_FIREBASE_APP_CHECK_SITE_KEY}"
      - "FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}"
      - "FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
    script: |
      #!/usr/bin/env bash
      corepack enable
      pnpm install --frozen-lockfile
      npx nuxi generate
      npx firebase-tools --project=$PROJECT_ID deploy --only=hosting --non-interactive

options:
  logging: CLOUD_LOGGING_ONLY