steps:
  - id: 'Restore'
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        storage_bucket="${PROJECT_ID}.firebasestorage.app"
        pnpm_storage_uri="gs://${storage_bucket}/pnpm-$(sha256sum pnpm-lock.yaml | cut -d' ' -f1).tgz"
        nuxt_storage_uri="gs://${storage_bucket}/nuxt-${SHORT_SHA}.tgz"
        
        if gsutil -q stat "${pnpm_storage_uri}"; then
          mkdir -p /workspace/.pnpm-store
          echo "--> Restoring PNPM cache from ${pnpm_storage_uri}"
          gsutil -q cp "${pnpm_storage_uri}" - | tar -xz -C /workspace/.pnpm-store
        fi
        
        if gsutil -q stat "${nuxt_storage_uri}"; then
          mkdir -p /workspace/.nuxt
          echo "--> Restoring NUXT cache from ${nuxt_storage_uri}"
          gsutil -q cp "${nuxt_storage_uri}" - | tar -xz -C /workspace/.nuxt
        fi

  - id: 'Install & Deploy'
    name: 'node:22'
    env:
      - "FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "FIREBASE_APP_CHECK_DEBUG=${_FIREBASE_APP_CHECK_DEBUG}"
      - "FIREBASE_APP_CHECK_SITE_KEY=${_FIREBASE_APP_CHECK_SITE_KEY}"
      - "FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}"
      - "FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
    script: |
      #!/usr/bin/env bash
      set -e
      corepack enable
      pnpm install --frozen-lockfile
      npx nuxi generate
      npx firebase-tools --project=$PROJECT_ID deploy --only=hosting --non-interactive

  - id: 'Cache'
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        storage_bucket="${PROJECT_ID}.firebasestorage.app"
        nuxt_storage_uri="gs://${storage_bucket}/nuxt-${SHORT_SHA}.tgz"
        
        if [ -d /workspace/.pnpm-store ]; then
          pnpm_storage_uri="gs://${storage_bucket}/pnpm-$(sha256sum pnpm-lock.yaml | cut -d' ' -f1).tgz"
          echo "--> Caching PNPM to ${pnpm_storage_uri}"
          tar -czf /tmp/pnpm-cache.tgz -C /workspace/.pnpm-store . 
          gsutil -q cp /tmp/pnpm-cache.tgz "${pnpm_storage_uri}"
        fi
        
        if [ -d /workspace/.nuxt ] && ! gsutil -q stat "${nuxt_storage_uri}"; then
          echo "--> Caching NUXT to ${nuxt_storage_uri}"
          tar -czf /tmp/nuxt-cache.tgz -C /workspace/.nuxt .
          gsutil -q cp /tmp/nuxt-cache.tgz "${nuxt_storage_uri}"
        fi

timeout: 300s
options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: 'pnpm-store'
      path: '/workspace/.pnpm-store'
    - name: 'nuxt-cache'
      path: '/workspace/.nuxt'
